title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs
baseurl: "SC_JTD_TEST"
url: "https://s-cox.github.io/"


